service: threat-intel-bot

provider:
  name: aws
  runtime: python3.7
  region: us-west-1
  stage: dev
  environment:
    SLACK_API_TOKEN: "${self:custom.secrets.SLACK_API_TOKEN}"
    SLACK_CHANNEL: "${self:custom.secrets.SLACK_CHANNEL}"
    PASSIVETOTAL_USERNAME: "${self:custom.secrets.PASSIVETOTAL_USERNAME}"
    PASSIVETOTAL_APIKEY: "${self:custom.secrets.PASSIVETOTAL_APIKEY}"
    VT_API_KEY: "${self:custom.secrets.VT_API_KEY}"
    MISP_API_KEY: "${self:custom.secrets.MISP_API_KEY}"
    MISP_BASE_URL: "${self:custom.secrets.MISP_BASE_URL}"
    JASK_API_KEY: "${self:custom.secrets.JASK_API_KEY}"
    JASK_BASE_URL: "${self:custom.secrets.JASK_BASE_URL}"

functions:
  query:
    handler: query.handler
    events:
      - http:
          path: query
          method: any
          request:
            passThrough: WHEN_NO_MATCH
  vt:
    handler: vt.handler
    events:
      - http:
          integration: LAMBDA
          path: vt
          method: any
          request:
            passThrough: WHEN_NO_MATCH

  misp:
    handler: misp.handler
    events:
      - http:
          integration: LAMBDA
          path: misp
          method: any
          request:
            passThrough: WHEN_NO_MATCH

  jask:
    handler: jask.handler
    events:
      - http:
          integration: LAMBDA
          path: jask
          method: any
          request:
            passThrough: WHEN_NO_MATCH

plugins:
  - serverless-python-requirements
custom:
  stage: ${opt:stage, self:provider.stage}
  secrets: ${file(secrets.yml):${self:custom.stage}}
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - secrets.yml
